In [1]:
import numpy as np
import pandas as pd

# 1.ndarray对象

In [3]:
np.array(object=[1,2,3], dtype = None, copy = True, order = None, subok = False, ndmin = 0)
# object:数组或嵌套的数列 dtype:数组元素的数据类型 copy:对象是否需要复制
# order:创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
# subok:默认返回一个与基类类型一致的数组 ndmin:指定生成数组的最小维度

array([1, 2, 3])

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a = np.array([[1,2,3],[4,5,6]])# 多于一个维度
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
a = np.array([1,2,3], dtype = complex)# 数据类型为复数
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [7]:
a = np.array([1,2,3], ndmin = 2)# 指定维度为2
print(a)

[[1 2 3]]


In [8]:
a = np.array([1,2,3], dtype = complex, ndmin = 2)# 指定维度为2，数据类型为复数
print(a)

[[1.+0.j 2.+0.j 3.+0.j]]


# 2.数据类型

In [10]:
np.dtype(object, align = False, copy = True)# object:要转换的数据 align:如果为true，填充字段使其类似C的结构体
# copy:生成dtype对象的新副本，如果为false，结果是内建数据类型对象的引用

dtype('O')

In [11]:
dt = np.dtype(np.int32)
print(dt)

int32


In [12]:
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [17]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a)
print(a['age'])

[(10,) (20,) (30,)]
[10 20 30]


In [19]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print(student)
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


# 3.数组属性

In [20]:
# ndarray.shape 这一数组属性返回一个包含数组维度的元组，这个元组的长度就是ndim属性(秩)。它也可以用于调整数组大小
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [29]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [36]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)
print(b.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [33]:
# ndarray.ndim 秩，即轴的数量或维度的数量
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [37]:
a = np.arange(24)
b = a.reshape(2,4,3)
print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [32]:
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


# 4.创建数组

In [42]:
# numpy.empty(shape, dtype = float, order = 'C') 返回一个给定形状和类型的新数组，元素不初始化
x = np.empty([3,2], dtype = int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [45]:
arr1 = np.arange(5)
print(arr1)

[0 1 2 3 4]


In [49]:
arr2 = np.linspace(0, 10, 5)# 0到10之间的5个数
print(arr2)

[ 0.   2.5  5.   7.5 10. ]


In [51]:
np.random.rand(2,3)# 生成2行3列的随机数
np.random.rand(2,3,4)# 生成2行3列4层的随机数
np.random.uniform(1,2,3)# 生成1到2之间的3个随机数

array([1.99771434, 1.89170229, 1.52372412])

# 5.切片和索引、迭代

In [52]:
a = np.arange(10)
s = slice(2,7,2)# 从索引2开始到索引7停止，间隔为2
print(a[s])

[2 4 6]


In [53]:
a = np.arange(10)
b = a[5]
print(b)

5


In [54]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
b = a[1:]
print(b)

[[3 4 5]
 [4 5 6]]


In [57]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
for x in np.nditer(a):
    print(x,end=' ')

0 5 10 15 20 25 30 35 40 45 50 55 

In [59]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
b = a.T
print(b)
for x in np.nditer(b):
    print(x,end=' ')

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [61]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
for x in np.nditer(a, order = 'C'):
    print(x,end=' ')
for x in np.nditer(a, order = 'F'):
    print(x,end='|')

0 5 10 15 20 25 30 35 40 45 50 55 0|20|40|5|25|45|10|30|50|15|35|55|

# 6.高级索引